# Generated by Django 5.1 on 2024-08-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_note_recommendation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Recommendation',
        ),
    ]
