# Generated by Django 5.1 on 2024-09-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0004_rename_note_recommendation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("patient", "Patient"), ("doctor", "Doctor")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="doctor_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
